name: handy-nginx

services:
  nginx:
    image: ghcr.io/zguydev/handy-nginx:1.28.0-alpine-slim
    container_name: handy-nginx
    hostname: handy-nginx
    restart: on-failure:2
    environment:
      TZ: "${TZ:-UTC}"
      NGINX_ENTRYPOINT_RELOAD_WATCHER: true
    volumes:
      - ./templates/main/:/etc/nginx/templates/main/:ro
      - ./templates/sites-available/:/etc/nginx/templates/sites-available/:ro
      - ./templates/conf.d/:/etc/nginx/templates/conf.d/:ro
      - ./templates/stream-conf.d/:/etc/nginx/templates/stream-conf.d/:ro
      - ./templates/common/:/etc/nginx/templates/common/:ro
      - ./nginx.env:/mount/nginx.env:ro
    ports:
      - "80:80"
    networks: [routing]
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  routing:
    name: routing
    driver: bridge
